"""
Perception layer — data ingestion and event stream construction.

Responsibilities:
- Define SensorEvent and DriverEvent dataclasses that represent raw inputs.
- Parse CSV files into typed event objects.
- Merge sensor and driver event streams into a single time-ordered sequence
  ready for the event loop (PF-02).
"""

from __future__ import annotations

import csv
from dataclasses import dataclass
from pathlib import Path
from typing import Union


# ---------------------------------------------------------------------------
# Domain event types
# ---------------------------------------------------------------------------

@dataclass(frozen=True, order=True)
class SensorEvent:
    """
    A single reading emitted by an on-board sensor.

    Attributes:
        timestamp:   Seconds since epoch (or relative mission time).
        sensor_id:   Unique identifier for the physical sensor.
        sensor_type: Category string, e.g. "LIDAR" or "Camera".
        data_value:  Numeric payload whose semantics depend on sensor_type.
        unit:        SI unit label, e.g. "m" or "px".
    """

    timestamp: float
    sensor_id: str
    sensor_type: str
    data_value: float
    unit: str


@dataclass(frozen=True, order=True)
class DriverEvent:
    """
    An action generated by the driver or the cockpit HMI.

    Attributes:
        timestamp:  Seconds at which the event was recorded.
        event_type: One of ENGAGE, DISENGAGE, or STEERING_FORCE.
        value:      Numeric payload (force in Newtons for STEERING_FORCE,
                    0.0 for ENGAGE / DISENGAGE).
    """

    timestamp: float
    event_type: str
    value: float


# Convenience union used in type hints across the codebase.
AnyEvent = Union[SensorEvent, DriverEvent]


# ---------------------------------------------------------------------------
# CSV readers
# ---------------------------------------------------------------------------

def read_sensor_events(path: Path) -> list[SensorEvent]:
    """
    Parse *sensor_log.csv* into a list of :class:`SensorEvent` objects.

    The CSV must have a header row with columns:
    ``timestamp, sensor_id, sensor_type, data_value, unit``

    Args:
        path: Absolute path to ``sensor_log.csv``.

    Returns:
        List of :class:`SensorEvent`, unsorted.

    Raises:
        FileNotFoundError: If *path* does not exist.
        ValueError:        If a row cannot be parsed.
    """
    events: list[SensorEvent] = []
    with path.open(newline="", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            events.append(
                SensorEvent(
                    timestamp=float(row["timestamp"]),
                    sensor_id=row["sensor_id"].strip(),
                    sensor_type=row["sensor_type"].strip(),
                    data_value=float(row["data_value"]),
                    unit=row["unit"].strip(),
                )
            )
    return events


def read_driver_events(path: Path) -> list[DriverEvent]:
    """
    Parse *driver_events.csv* into a list of :class:`DriverEvent` objects.

    The CSV must have a header row with columns:
    ``timestamp, event_type, value``

    Args:
        path: Absolute path to ``driver_events.csv``.

    Returns:
        List of :class:`DriverEvent`, unsorted.

    Raises:
        FileNotFoundError: If *path* does not exist.
        ValueError:        If a row cannot be parsed.
    """
    events: list[DriverEvent] = []
    with path.open(newline="", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            events.append(
                DriverEvent(
                    timestamp=float(row["timestamp"]),
                    event_type=row["event_type"].strip(),
                    value=float(row["value"]),
                )
            )
    return events


# ---------------------------------------------------------------------------
# Stream merger
# ---------------------------------------------------------------------------

def merge_events(
    sensor_events: list[SensorEvent],
    driver_events: list[DriverEvent],
) -> list[AnyEvent]:
    """
    Merge two event lists into a single time-ordered stream (PF-02).

    When two events share the same timestamp, driver events are placed
    **before** sensor events so that state transitions caused by the driver
    are visible to the sensor processing logic within the same tick.

    Args:
        sensor_events: List of :class:`SensorEvent` objects.
        driver_events: List of :class:`DriverEvent` objects.

    Returns:
        Combined list sorted by ``(timestamp, event_kind_priority)`` where
        driver events have lower sort key (processed first).
    """

    def sort_key(event: AnyEvent) -> tuple[float, int]:
        # Driver events (priority 0) come before sensor events (priority 1)
        # at identical timestamps.
        kind_priority = 0 if isinstance(event, DriverEvent) else 1
        return (event.timestamp, kind_priority)

    combined: list[AnyEvent] = [*sensor_events, *driver_events]
    combined.sort(key=sort_key)
    return combined
